---
abstract: 'CGI-based Ext.Direct server'
author:
  - 'Alexander Tokarev <tokarev@cpan.org>'
build_requires:
  WWW::Mechanize: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-ExtDirect-Server
no_index:
  directory:
    - t
    - inc
requires:
  CGI::ExtDirect: 1.12
  RPC::ExtDirect: 1.31
resources:
  bugtracker: http://github.com/nohuhu/RPC-ExtDirect-Server/issues
  repository: http://github.com/nohuhu/RPC-ExtDirect-Server
version: 0.01
