---
abstract: 'A tiny but capable pure Perl Ext.Direct server'
author:
  - 'Alex Tokarev <tokarev@cpan.org>'
build_requires:
  HTTP::Tiny: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RPC-ExtDirect-Server
no_index:
  directory:
    - t
    - inc
requires:
  CGI::ExtDirect: '3.00'
  HTTP::Server::Simple: '0.44'
  RPC::ExtDirect: '3.00'
resources:
  bugtracker: http://github.com/nohuhu/RPC-ExtDirect-Server/issues
  repository: http://github.com/nohuhu/RPC-ExtDirect-Server
version: '1.00'
